/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-11-22 15:38:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.tackit.DTO.Board;
import java.util.List;
import com.tackit.DTO.Pin;
import java.util.ArrayList;
import com.tackit.DTO.User;
import javax.jws.soap.SOAPBinding.Use;

public final class DataView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

		User userObj = (User) session.getAttribute("userInfo");
		boolean uListFlag = userObj.getBoardList().isEmpty();
		boolean fllwdListFlag = userObj.getFollowedBoardList().isEmpty();
		boolean feed = userObj.getFeedPinList().isEmpty();
		
		
	
      out.write('\r');
      out.write('\n');
      out.write('	');

		User usrObj = (User) session.getAttribute("userInfo");
		List<String> bbList = new ArrayList<String>();
		
		for (Board board : usrObj.getBoardList()) {
			bbList.add(board.getBoardName());
		}
		for (Board board : usrObj.getFollowedBoardList()) {
			bbList.add(board.getBoardName());
		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

		if (!feed) {
			ArrayList<Pin> pFeedList = (ArrayList<Pin>) userObj
					.getFeedPinList();
			int i;
			int j;
	
      out.write("\r\n");
      out.write("\t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t");

			for (i = 0; i < pFeedList.size(); i++) {
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				for (j = i; j < i + 4; j++) {
							if (j == pFeedList.size()) {

								for (int k = j; k < i + 4; k++) {
			
      out.write("\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t\t");

				}
								break;
							} else {
			
      out.write("\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t<h4>");
      out.print(pFeedList.get(i).getPinName());
      out.write("</h4>\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(pFeedList.get(j).getPinLink());
      out.write("\" target=\"_blank\"><img\r\n");
      out.write("\t\t\t\t\talt=\"\" src=\"");
      out.print(pFeedList.get(j).getImgLocation());
      out.write("\"></a> \r\n");
      out.write("\t\t\t\t\t</center>\t\r\n");
      out.write("\t\t\t\t\t<br> <div align=\"left\" style=\"color:#A8A8A8;\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t");
      out.print(pFeedList.get(j).getPinDescription());
      out.write("<br> \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<a href=\"#");
      out.print(j);
      out.write("\"\r\n");
      out.write("\t\t\t\tclass=\"btn btn-danger\" data-toggle=\"modal\">TackIT</a> <br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"");
      out.print(j);
      out.write("\" class=\"modal fade\" aria-hidden=\"false\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h2>TackIT</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<form class=\"form-horizontal\" action=\"PinInfo\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<table cellpadding=\"10px\" cellspacing=\"10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><label>URL</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><input class=\"form-control\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\trequired=\"true\" type=\"text\" class=\"span4\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdisabled=\"true\" value=\"");
      out.print(pFeedList.get(j).getPinLink());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(j );
      out.write("\" name=\"pNo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(pFeedList.get(j).getPinLink());
      out.write("\" name=\"pLink\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(pFeedList.get(j).getPinName());
      out.write("\" name=\"pName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(pFeedList.get(j).getImgLocation());
      out.write("\" name=\"pImage\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(pFeedList.get(j).getpGenre());
      out.write("\" name=\"pGenre\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><label>Board</label></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><select class=\"form-control\" required name=\"pBoard\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");

															for (String boardName : bbList) {
														
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option>");
      out.print(boardName);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");

															}
														
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><label>Description</label></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><textarea class=\"form-control\" class=\"span4\" autofocus\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"pDesc\" required placholder=\"Description to the Pin\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-success\" value=\"TackIT\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn\" data-dismiss=\"modal\" aria-hidden=\"true\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t");

				}
						}
						i = j - 1;
			
      out.write("\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");

		} else {
	
      out.write("\r\n");
      out.write("\t<h3>\r\n");
      out.write("\t\t");
      out.print("No feeds available");
      out.write("\r\n");
      out.write("\t</h3>\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
